Restaurant views templates
KarthikrajanTP/RestaurantApp pull request #5
Opened 2024-08-08 06:22 UTC by KarthikrajanTP

- Created List and Detail view for restaurants
- Created ListView for spotlight, bookmarked and visited restaurants
- Added image field in Dish model
- Created DishListView and template
- Created forms to handle reviews

2024-08-08 06:54 UTC, shantanutomarr requested changes

2024-08-08 06:54 UTC, shantanutomarr commented on restaurants/models.py
> +    image = models.ImageField(upload_to='dish_photos/', null=True, blank=True)
Create a separate PR to add this model field and the related migration. Model changes should be done in a separate commit.

2024-08-08 06:54 UTC, shantanutomarr commented on templates/restaurant_detail.html
> +                    {{ review_form.rating|add_class:"block w-full mt-1 rounded-lg border-gray-300 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50" }}
This is a great opportunity for you to learn about widget_tweaks package. We have used this package extensively in testpress codebase.
https://pypi.org/project/django-widget-tweaks/

Check ``{% render_field form.title class+="css_class_1 css_class_2" %}

2024-08-08 06:54 UTC, shantanutomarr commented on restaurants/views.py
See if you can implement the django_filters for sorting too. I am attaching a screenshot of a filter used in testpress. Check the `o`  field Ignore everything else.

![Screenshot from 2024-08-08 12-06-48](https://github.com/user-attachments/assets/ab11fa0b-354e-4a50-a9a5-2f0fa03abd27)

2024-08-08 06:54 UTC, shantanutomarr commented on restaurants/views.py
> +            form = ReviewForm(request.POST)
Extract this to a new method called something like `_is_update_review_form()`

2024-08-08 06:54 UTC, shantanutomarr commented on restaurants/views.py
> +            review.save()
Extract these to separate method having intent revealing name.

2024-08-08 06:54 UTC, shantanutomarr commented on restaurants/views.py
> +        return Dish.objects.filter(restaurant_id=restaurant_id)
```suggestion
        return Dish.objects.filter(restaurant_id=self.kwargs.get('pk'))
```

2024-08-08 06:54 UTC, shantanutomarr commented on restaurants/views.py
> +        return Restaurant.objects.filter(reviews__user=user, reviews__visited=True).distinct()
```suggestion
        return Restaurant.objects.filter(reviews__user=self.request.user, reviews__visited=True).distinct()
```

2024-08-08 06:59 UTC, shantanutomarr commented on restaurants/views.py
> +            form = ReviewForm(request.POST)
```suggestion
        user_review = restaurant.reviews.filter(user=request.user).first()
        form = ReviewForm(request.POST, instance=user_review)
      
```

2024-08-08 12:09 UTC, KarthikrajanTP commented
Closing this PR to see the changes done by merging the models branch to master branch.

2024-08-09 04:38 UTC, shantanutomarr approved these changes

2024-08-09 04:41 UTC, merged